// app3_vue/src/App.vue
<template>
  <div>
    <h1>
      {{ message }}
    </h1>
  </div>
</template>

<script>
export default {
  data() {
    return { message: "Microfrontend - Vue App" };
  },
};
</script>

<style scoped>
div {
  background-color: orange;
  margin: 2rem;
  padding: 2rem;
  text-align: center;
  color: white;
  border-radius: 8px
}
</style>

// app2_react/src/App.js
import React from "react";

const App = () => {
  return (
    <div
      style={{
        margin: "2rem",
        padding: "2rem",
        textAlign: "center",
        backgroundColor: "blue",
        color: "white",
        borderRadius: "8px"
      }}
    >
      <h1>Microfrontend - React App</h1>
    </div>
  );
};

export default App;
